# Generated by Django 2.2.4 on 2020-08-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200821_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='filled_by',
        ),
        migrations.AddField(
            model_name='job',
            name='filled_by',
            field=models.ManyToManyField(related_name='job_filled_by', to='main.User'),
        ),
    ]
