# Generated by Django 2.2.4 on 2020-08-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
