# Generated by Django 2.2.4 on 2020-08-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=65)),
                ('last_name', models.TextField(max_length=65)),
                ('email', models.CharField(max_length=65)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
