# Generated by Django 2.2.4 on 2020-08-21 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='job',
            name='uploaded_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_jobs', to='main_app.User'),
        ),
    ]
