# Generated by Django 2.2.4 on 2020-08-21 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200821_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='uploaded_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_jobs', to='main_app.User'),
        ),
    ]
