# Generated by Django 2.2.4 on 2020-08-21 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200821_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=65)),
                ('location', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('filled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_filled_by', to='main_app.User')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_jobs', to='main_app.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
